### ISSUE TITLE
Could you share your model? Thanks for your work

### ISSUE THREAD

**Issue by waynamigo** [lppllppl920/DenseDescriptorLearning-Pytorch#5]
Hi Dr.Liu @lppllppl920 , Could you share the pre-trained model?

I got my model on our endoscope datasets, but the performance was not as good as the demo. The results are like:
![](https://ftp.bmp.ovh/imgs/2021/04/8f789f6565b048a1.png)
I think the feature of our datasets and yours are very similar, so I hope you can share the pretrained model with me for comparing the performance.

Thank you for your work!

**Comment by lppllppl920** [comment]
hello, I’m sorry but we cannot share the pretrained model because the related dataset is not available publicly.  What are the images that you are showing? Monocular depth network only works well in cases where the visual cue from a single image is enough to determine its depth. Try to judge the networks performance with human performance as the upper bound.


Sorry, I thought this is the issue on my mono depth repo. In terms of the descriptor learning, a lot of the factors could affect the final results. Try to increase the number of candidate keypoints per image to increase the reconstruction density.

**Comment by waynamigo** [comment]
Ok I understand.
That image is one frame of the video overlayed with 3Dpoints generated by my model, I'll try to get better results.
Thank you very much for quick reply.
